const path = require('path');

const BUFF_COOKIE = "";
const EMPIRE_COOKIE = '';
const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36';
const UUID = '';
const PINCODE = '123456';
const TRADE_URL = '';
const API_KEY = '';

exports.BUFF_FEES = 1;
exports.BUFF_RATE = 3.7;
exports.EMPIRE_PROFIT_THRESHOLD = 15.0;
exports.MIN_PRICE = 1;
exports.USER_ID = 12345623;
exports.BUFF_COOKIE = BUFF_COOKIE;

// 5etop config
// exports.RATE_5E_PROFIT = 14.5;
exports.DISCORD_HOOK = 'https://discordapp.com/api/webhooks/955795711147003935/AAPSQCoSfbR1Y2FgtkHLcjnbbmfzlcZTziMWkvZ3vvaTTo4F86-bU0khkqMu6vdMHkrC';
exports.DISCORD_USER_ID = '418785866111123467';
// hours
exports.TIME_CHECK = 0.083;


exports.CONST = {
    BUFF: {
        HEADERS: {
            headers: {
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                "Accept-Encoding": "gzip, deflate, br",
                "Accept-Language": "vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7",
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "Cookie": BUFF_COOKIE,
                "Host": "buff.163.com",
                "Pragma": "no-cache",
                "Referer": "https://buff.163.com/market/?game=csgo",
                "Sec-Fetch-Dest": "document",
                "Sec-Fetch-Mode": "navigate",
                "Sec-Fetch-Site": "none",
                "Upgrade-Insecure-Requests": 1,
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/87.0.152 Chrome/81.0.4044.152 Safari/537.36",
                "X-Requested-With": "XMLHttpRequest",
            }
        },
        API: {
            CSGO: 'https://buff.163.com/api/market/goods?game=csgo&page_size=80&sort_by=price.desc'
        },
        DB_FILE: path.resolve(__dirname, 'buffcrawl.json'),
        DB_DOPPLER_FILE: path.resolve(__dirname, 'buffdopplercrawl.json'),
    },
    EMPIRE: {
        HEADERS: {
            'headers': {
                'authority': 'csgoempire.com',
                'accept': 'application/json, text/plain, */*',
                // 'accept-encoding': 'gzip, deflate, br',
                'accept-language': 'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7',
                'cache-control': 'no-cache',
                'cookie': EMPIRE_COOKIE,
                'pragma': 'no-cache',
                'referer': 'https://csgoempire.com/withdraw',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': USER_AGENT,
                'x-empire-device-identifier': UUID
            }
        },
        API: {
            TOKEN: 'https://csgoempire.com/api/v2/user/security/token',
            WITHDRAW: 'https://csgoempire.com/api/v2/trade/withdraw',
            STEAM_URL: 'https://csgoempire.com/api/v2/trade/steam/url',
            METADATA: 'https://csgoempire.com/api/v2/metadata',
            BID: 'https://csgoempire.com/api/v2/trade/auction/place-bid'
        },
        UUID: UUID,
        PINCODE: PINCODE,
        COOKIE: EMPIRE_COOKIE,
        USER_AGENT: USER_AGENT,
        TRADE_URL: TRADE_URL,
        API_KEY: API_KEY,
        OUTPUT_ITEM: path.resolve(__dirname, 'output.txt'),
        ERROR_ITEM: path.resolve(__dirname, 'error.txt')
    }
}

exports.BLACK_LIST = [
    'Sticker | Spirit (Foil) | 2020 RMR',
    'USP-S | Purple DDPAT (Factory New)',
    'Patch | FaZe Clan (Gold) | Stockholm 2021',
]

exports.AUTO_WITHDRAW_ITEMS = [
    "M4A1-S | Hyper Beast (Well-Worn)",
    "StatTrak™ M4A4 | Buzz Kill (Field-Tested)",
    "SG 553 | Cyrex (Factory New)",
    "M4A1-S | Cyrex (Field-Tested)",
    "AK-47 | Orbit Mk01 (Factory New)",
    "AK-47 | Emerald Pinstripe (Factory New)",
    "AK-47 | Frontside Misty (Field-Tested)",
    "AK-47 | Aquamarine Revenge (Battle-Scarred)",
    "AK-47 | Redline (Field-Tested)",
    "M4A4 | The Emperor (Field-Tested)",
    "M4A4 | Bullet Rain (Minimal Wear)",
    "M4A4 | The Coalition (Field-Tested)",
    "AK-47 | Slate (Factory New)",
    "StatTrak™ AK-47 | Phantom Disruptor (Field-Tested)",
    "M4A1-S | Control Panel (Field-Tested)",
    "StatTrak™ M4A4 | Neo-Noir (Field-Tested)",
    "AWP | Elite Build (Minimal Wear)",
    "FAMAS | Commemoration (Minimal Wear)",
    "M4A4 | X-Ray (Factory New)",
    "StatTrak™ M4A1-S | Leaded Glass (Field-Tested)",
    "AWP | Corticera (Minimal Wear)",
    "AWP | Sun in Leo (Minimal Wear)",
    "AK-47 | Point Disarray (Field-Tested)",
    "M4A4 | Cyber Security (Minimal Wear)",
    "AK-47 | Legion of Anubis (Field-Tested)",
    "StatTrak™ AK-47 | Slate (Field-Tested)",
    "AK-47 | Cartel (Factory New)",
    "SSG 08 | Dragonfire (Minimal Wear)",
    "M4A1-S | Leaded Glass (Factory New)", 
    "AWP | Atheris (Factory New)",
    "AK-47 | Phantom Disruptor (Factory New)",
    "FAMAS | Meltdown (Factory New)",
    "M4A1-S | Nightmare (Field-Tested)",
    "SG 553 | Colony IV (Minimal Wear)",
    "StatTrak™ AK-47 | Slate (Battle-Scarred)",
    "M4A1-S | Decimator (Field-Tested)",
    "StatTrak™ M4A4 | Desolate Space (Field-Tested)",
    "AK-47 | Safety Net (Factory New)",
    "AK-47 | Orbit Mk01 (Minimal Wear)",
    "M4A4 | Buzz Kill (Minimal Wear)",
    "AK-47 | Legion of Anubis (Battle-Scarred)",
    "AWP | Sun in Leo (Field-Tested)",
    "M4A4 | Tooth Fairy (Factory New)",
    "SSG 08 | Dragonfire (Field-Tested)",
    "M4A4 | 龍王 (Dragon King) (Minimal Wear)",
    "AWP | Fever Dream (Factory New)",
    "AK-47 | Emerald Pinstripe (Minimal Wear)",
    "AK-47 | Blue Laminate (Factory New)",
    "AK-47 | Phantom Disruptor (Minimal Wear)",
    "M4A1-S | Leaded Glass (Minimal Wear)",
    "M4A1-S | Nitro (Factory New)",
    "StatTrak™ AK-47 | Elite Build (Minimal Wear)",
    "M4A4 | Desolate Space (Minimal Wear)",
    "M4A4 | In Living Color (Field-Tested)",
    "M4A4 | Buzz Kill (Field-Tested)",
    "AK-47 | Safety Net (Minimal Wear)",
    "M4A4 | Spider Lily (Factory New)",
    "M4A1-S | Night Terror (Factory New)",
    "M4A4 | Neo-Noir (Field-Tested)",
    "AUG | Carved Jade (Factory New)",
    "AUG | Syd Mead (Factory New)",
    "AK-47 | Slate (Minimal Wear)",
    "AK-47 | Emerald Pinstripe (Field-Tested)",
    "SG 553 | Cyrex (Minimal Wear)",
    "M4A1-S | Leaded Glass (Field-Tested)",
    "FAMAS | Mecha Industries (Factory New)",
    "AWP | Fever Dream (Field-Tested)",
    "M4A4 | Royal Paladin (Field-Tested)",
    "AK-47 | Phantom Disruptor (Field-Tested)",
    "AWP | Mortis (Factory New)",
    "AUG | Momentum (Minimal Wear)",
    "FAMAS | Meltdown (Minimal Wear)",
    "AWP | Atheris (Minimal Wear)",
    "AK-47 | Cartel (Field-Tested)",
    "AK-47 | Elite Build (Factory New)",
    "SG 553 | Desert Blossom (Factory New)",
    "M4A4 | The Battlestar (Minimal Wear)",
    "SG 553 | Cyrex (Field-Tested)",
    "AK-47 | Safety Net (Field-Tested)",
    "AWP | Exoskeleton (Factory New)",
    "M4A4 | Desolate Space (Field-Tested)",
    "AWP | PAW (Factory New)",
    "M4A1-S | Nitro (Minimal Wear)",
    "M4A4 | Tooth Fairy (Field-Tested)",    
    // "AWP | Asiimov (Field-Tested)",
    // "AWP | Asiimov (Well-Worn)",
    // "AWP | Asiimov (Battle-Scarred)",
    // "AWP | Redline (Field-Tested)",
    // "AWP | Redline (Minimal Wear)",
    // "AWP | Oni Taiji (Factory New)",
    // "Galil AR | Cerberus (Factory New)",
    // "AWP | Oni Taiji (Minimal Wear)",
    // "AWP | Oni Taiji (Field-Tested)",
    // "AWP | Oni Taiji (Well-Worn)",
    // "AWP | Neo-Noir (Factory New)",
    // "AWP | Neo-Noir (Minimal Wear)",
    // "AWP | Neo-Noir (Field-Tested)",
    // "AWP | Neo-Noir (Well-Worn)",
    // "AWP | Neo-Noir (Battle-Scarred)",
    // "AWP | Wildfire (Factory New)",
    // "AWP | Wildfire (Minimal Wear)",
    // "AWP | Wildfire (Field-Tested)",
    // "AK-47 | The Empress (Factory New)",
    // "AK-47 | The Empress (Minimal Wear)",
    // "AK-47 | The Empress (Field-Tested)",
    // "AK-47 | The Empress (Well-Worn)",
    // "AK-47 | Redline (Field-Tested)",
    // "AK-47 | Redline (Minimal Wear)",
    // "StatTrak™ AK-47 | Redline (Field-Tested)",
    // "StatTrak™ AK-47 | Redline (Minimal Wear)",
    // "StatTrak™ AK-47 | Fuel Injector (Field-Tested)",
    // "AK-47 | Fuel Injector (Field-Tested)",
    // "AK-47 | Fuel Injector (Minimal Wear)",
    // "AK-47 | Fuel Injector (Well-Worn)",
    // "AK-47 | Asiimov (Factory New)",
    // "AK-47 | Asiimov (Minimal Wear)",
    // "AK-47 | Asiimov (Field-Tested)",
    // "AK-47 | Asiimov (Battle-Scarred)",
    // "StatTrak™ AK-47 | Asiimov (Field-Tested)",
    // "StatTrak™ AK-47 | Asiimov (Minimal Wear)",
    // "StatTrak™ AK-47 | The Empress (Field-Tested)",
    // "StatTrak™ AK-47 | The Empress (Minimal Wear)",
    // "AK-47 | Fire Serpent (Field-Tested)",
    // "AK-47 | Fire Serpent (Minimal Wear)",
    // "AK-47 | Aquamarine Revenge (Minimal Wear)",
    // "AK-47 | Aquamarine Revenge (Field-Tested)",
    // "AK-47 | Vulcan (Minimal Wear)",
    // "AK-47 | Vulcan (Field-Tested)",
    // "StatTrak™ AK-47 | Vulcan (Field-Tested)",
    // "StatTrak™ AK-47 | Vulcan (Minimal Wear)",
    // "M4A4 | Asiimov (Field-Tested)",
    // "M4A4 | Asiimov (Well-Worn)",
    // "StatTrak™ M4A4 | The Emperor (Field-Tested)",
    // "StatTrak™ M4A4 | The Emperor (Minimal Wear)",
    // "M4A4 | The Emperor (Minimal Wear)",
    // "M4A4 | The Emperor (Field-Tested)",
    // "M4A4 | Neo-Noir (Minimal Wear)",
    // "M4A4 | Neo-Noir (Field-Tested)",
    // "StatTrak™ M4A4 | Neo-Noir (Field-Tested)",
    // "StatTrak™ M4A4 | Neo-Noir (Minimal Wear)",
    // "StatTrak™ M4A4 | Buzz Kill (Minimal Wear)",
    // "StatTrak™ M4A4 | Buzz Kill (Field-Tested)",
    // "Desert Eagle | Blaze (Factory New)",
    // "USP-S | Neo-Noir (Field-Tested)",
    // "USP-S | Neo-Noir (Minimal Wear)",
    // "StatTrak™ USP-S | Neo-Noir (Minimal Wear)",
    // "StatTrak™ USP-S | Neo-Noir (Field-Tested)",
    // "USP-S | Kill Confirmed (Factory New)",
    // "USP-S | Kill Confirmed (Minimal Wear)",
    // "USP-S | Kill Confirmed (Field-Tested)",
    // "StatTrak™ USP-S | Kill Confirmed (Field-Tested)",

    

    // // own
    // "AWP | Fever Dream (Minimal Wear)",
    // "AWP | Fever Dream (Field-Tested)",
    // "AWP | Fever Dream (Factory New)",
    // "StatTrak™ AWP | Fever Dream (Factory New)",
    // "StatTrak™ AWP | Fever Dream (Minimal Wear)",
    // "StatTrak™ AWP | Fever Dream (Field-Tested)",
    // "AWP | BOOM (Minimal Wear)",
    // "StatTrak™ AWP | Neo-Noir (Factory New)",
    // "P90 | Asiimov (Factory New)",
    // "P90 | Asiimov (Minimal Wear)",
    // "P90 | Asiimov (Field-Tested)",
    // "StatTrak™ AWP | Asiimov (Field-Tested)",
    // "M4A4 | Asiimov (Battle-Scarred)",
    // "Glock-18 | Water Elemental (Factory New)",
    // "P250 | Asiimov (Minimal Wear)",
    // "P250 | Asiimov (Field-Tested)",
    // "P250 | See Ya Later (Factory New)",
    // "AK-47 | Neon Revolution (Field-Tested)",
    // "AK-47 | Neon Revolution (Minimal Wear)",
    // "AK-47 | Neon Revolution (Factory New)",
    // "StatTrak™ AK-47 | Neon Revolution (Field-Tested)",
    // "AWP | Corticera (Minimal Wear)",
    // "AK-47 | Safety Net (Field-Tested)",
    // "AK-47 | Safety Net (Factory New)",
    // "AWP | Hyper Beast (Minimal Wear)",
    // "AWP | Hyper Beast (Factory New)",
    // // "'The Doctor' Romanov | Sabre",
    // "Special Agent Ava | FBI",
    // "StatTrak™ AK-47 | Bloodsport (Field-Tested)",
    // "M4A4 | 龍王 (Dragon King) (Minimal Wear)",
    // "M4A4 | 龍王 (Dragon King) (Field-Tested)",
    // "SSG 08 | Dragonfire (Minimal Wear)",
    // "SSG 08 | Dragonfire (Factory New)",
    // "USP-S | Orion (Factory New)",
    // "USP-S | Orion (Minimal Wear)",

    // "Desert Eagle | Code Red (Factory New)",
    // "Desert Eagle | Code Red (Minimal Wear)",
    // "Desert Eagle | Code Red (Field-Tested)",
    // "StatTrak™ Desert Eagle | Code Red (Field-Tested)",
    // "StatTrak™ Desert Eagle | Code Red (Minimal Wear)",
    // "Desert Eagle | Golden Koi (Factory New)",
    // "Desert Eagle | Mecha Industries (Factory New)",
    // "Desert Eagle | Mecha Industries (Minimal Wear)",
    // "StatTrak™ Desert Eagle | Mecha Industries (Minimal Wear)",
    // "StatTrak™ Desert Eagle | Mecha Industries (Factory New)",
    // "Desert Eagle | Kumicho Dragon (Factory New)",
    // "Desert Eagle | Kumicho Dragon (Minimal Wear)",
    // "Desert Eagle | Kumicho Dragon (Field-Tested)",
    // "StatTrak™ Desert Eagle | Kumicho Dragon (Field-Tested)",
    // "StatTrak™ Desert Eagle | Kumicho Dragon (Minimal Wear)",
    // "StatTrak™ Desert Eagle | Kumicho Dragon (Factory New)",
    // "StatTrak™ Desert Eagle | Conspiracy (Minimal Wear)",
    // "StatTrak™ Desert Eagle | Conspiracy (Factory New)",
    // "Desert Eagle | Conspiracy (Factory New)",
    // "Desert Eagle | Conspiracy (Minimal Wear)",
    // "Desert Eagle | Cobalt Disruption (Factory New)",
    // "Desert Eagle | Cobalt Disruption (Minimal Wear)",
    // "StatTrak™ Desert Eagle | Cobalt Disruption (Factory New)",
    // "Desert Eagle | Hypnotic (Factory New)",
    // "Desert Eagle | Crimson Web (Factory New)",
    // "Desert Eagle | Crimson Web (Minimal Wear)",
    // "Desert Eagle | Emerald Jörmungandr (Factory New)",
    // "Desert Eagle | Emerald Jörmungandr (Minimal Wear)",
    // "Desert Eagle | Sunset Storm 壱 (Factory New)",
    // "Desert Eagle | Sunset Storm 弐 (Factory New)",
    // "Desert Eagle | Blaze (Factory New)",

    // "AUG | Chameleon (Factory New)",
    // "AUG | Chameleon (Minimal Wear)",
    // "AUG | Death by Puppy (Factory New)",
    // "AUG | Death by Puppy (Minimal Wear)",
    // "AUG | Momentum (Factory New)",
    // "AUG | Momentum (Minimal Wear)",
    // "StatTrak™ AUG | Momentum (Minimal Wear)",
    // "AUG | Stymphalian (Factory New)",
    // "AUG | Stymphalian (Minimal Wear)",
    // "StatTrak™ AUG | Stymphalian (Minimal Wear)",
    // "AUG | Syd Mead (Factory New)",
    // "AUG | Syd Mead (Minimal Wear)",
    // "AUG | Bengal Tiger (Minimal Wear)",
    // "AUG | Arctic Wolf (Factory New)",
    // "AUG | Arctic Wolf (Minimal Wear)",
    // "StatTrak™ AUG | Arctic Wolf (Minimal Wear)",
    // "StatTrak™ AUG | Arctic Wolf (Factory New)",
    // "StatTrak™ AUG | Aristocrat (Factory New)",
    // "StatTrak™ AUG | Aristocrat (Minimal Wear)",
    // "AUG | Torque (Factory New)",
    // "AUG | Torque (Minimal Wear)",
    // "StatTrak™ AUG | Torque (Minimal Wear)",
    // "AUG | Flame Jörmungandr (Factory New)",

    // "M4A1-S | Decimator (Factory New)",
    // "M4A1-S | Decimator (Minimal Wear)",
    // "M4A1-S | Mecha Industries (Factory New)",
    // "M4A1-S | Mecha Industries (Minimal Wear)",
    // "M4A1-S | Mecha Industries (Field-Tested)",
    // "M4A1-S | Hyper Beast (Minimal Wear)",
    // "M4A1-S | Hyper Beast (Field-Tested)",
    // "M4A1-S | Golden Coil (Minimal Wear)",
    // "M4A1-S | Golden Coil (Field-Tested)",
    // "M4A1-S | Nightmare (Factory New)",
    // "M4A1-S | Nightmare (Minimal Wear)",
    // "M4A1-S | Cyrex (Factory New)",
    // "M4A1-S | Cyrex (Minimal Wear)",
    // "M4A1-S | Icarus Fell (Factory New)",
    // "M4A1-S | Player Two (Minimal Wear)",
    // "M4A1-S | Player Two (Field-Tested)",
    // "M4A1-S | Guardian (Factory New)",
    // "M4A1-S | Guardian (Minimal Wear)",
    // "M4A1-S | Hot Rod (Factory New)",
    // "M4A1-S | Atomic Alloy (Factory New)",
    // "M4A1-S | Atomic Alloy (Minimal Wear)",
    // "M4A1-S | Chantico's Fire (Minimal Wear)",
    // "M4A1-S | Chantico's Fire (Field-Tested)",
    // "M4A1-S | Knight (Factory New)",

    // "AK-47 | Neon Rider (Factory New)",
    // "AK-47 | Neon Rider (Minimal Wear)",
    // "AK-47 | Neon Rider (Field-Tested)",
    // "AK-47 | Bloodsport (Factory New)",
    // "AK-47 | Bloodsport (Minimal Wear)",
    // "AK-47 | Bloodsport (Field-Tested)",
    // "AK-47 | Wasteland Rebel (Minimal Wear)",
    // "AK-47 | Wasteland Rebel (Field-Tested)",
    // "AK-47 | Jaguar (Minimal Wear)",
    // "AK-47 | Jaguar (Field-Tested)",
    // "AK-47 | Phantom Disruptor (Factory New)",
    // "AK-47 | Phantom Disruptor (Minimal Wear)",
    // "AK-47 | Phantom Disruptor (Field-Tested)",
    // "AK-47 | Point Disarray (Factory New)",
    // "AK-47 | Point Disarray (Minimal Wear)",
    // "AK-47 | Point Disarray (Field-Tested)",
    // "AK-47 | Frontside Misty (Factory New)",
    // "AK-47 | Frontside Misty (Minimal Wear)",
    // "AK-47 | Frontside Misty (Field-Tested)",
    // "AK-47 | Cartel (Factory New)",
    // "AK-47 | Cartel (Minimal Wear)",
    // "AK-47 | Cartel (Field-Tested)",
    // "AK-47 | Hydroponic (Factory New)",
    // "AK-47 | Hydroponic (Minimal Wear)",
    // "AK-47 | Black Laminate (Minimal Wear)",

    // "Glock-18 | Vogue (Factory New)",
    // "Glock-18 | Vogue (Minimal Wear)",
    // "Glock-18 | Vogue (Field-Tested)",

    // "AWP | Containment Breach (Factory New)",
    // "AWP | Containment Breach (Minimal Wear)",
    // "AWP | Containment Breach (Field-Tested)",

    // "MAC-10 | Neon Rider (Factory New)",
    // "M4A4 | Desolate Space (Field-Tested)",
    // "M4A4 | Desolate Space (Factory New)",
    // "M4A4 | Desolate Space (Minimal Wear)",
    // "USP-S | Neo-Noir (Factory New)",
]

exports.DWORD = "Doppler (Factory New)";
exports.PHASE_STYLE = ["Ruby", "Sapphire", "Black Pearl", "Emerald", "Phase 1", "Phase 2", "Phase 3", "Phase 4"];
exports.PAINT_DATA = [
    { id: 871747, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 43011, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 43104, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 42402, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 42734, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 871861, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 871723, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 871877, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 871722, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 42832, paintIndex: [null, null, null, 568, 569, 570, 571, 572] },
    { id: 42998, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 43091, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 42389, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 769474, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 42720, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 769438, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 42917, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 42486, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 42636, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 42818, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 769477, paintIndex: [415, 416, 417, null, 418, 419, 420, 421] },
    { id: 43186, paintIndex: [415, 619, 617, null, 418, 618, 420, 421] },
    { id: 42555, paintIndex: [415, 619, 617, null, 418, 618, 420, 421] },
    { id: 769500, paintIndex: [415, 416, 417, null, 852, 853, 854, 855] },
];
